apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:AaQ1VoCsclim8lKTGfTAP6+T2d1m0LSBsg==,iv:rx6fEQ0f0P32WndoRqj4No2p6rKd50l6Er/HleqD/lM=,tag:iA3FmgHoeKsa9Ol+aIEOFA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:kGrU97eG/HfXEsxxuLFUQd9117vs7zNk3NTIBTjaMQnmBMUoFw==,iv:mdFugpBftxN562nQhO62LUZakZIrbgD4fCkSQfL69Dc=,tag:1ChgYPrwye0WhqmAssrg4A==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:xOx4+AFGeq2vhsAcx6kTzw==,iv:Nw+V5d0X8/aXH2SyJkw9Tjt1Hzstqj3D+fDCo9Q2lwQ=,tag:oQyc/fVkqRMwk/fRRcF3UA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxj35hpuyzh8zpgsxs3tg40wdm79vttlra35q88sdefdsqh3pgfqfppfjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdXRnMUtHdytadjhJa1BF
            bVBGMHJNUEtmeVB4WmhoMlViT2ZaaXB3OVE4ClVNanlvNlR6MTZUaHdrVjlaMUZV
            RVZwRzNMeTJRWnlkWEJOUHJqVXFEd1EKLS0tIGhySXA1MXIxOUxld0pxWmd5dFg4
            UVI0SXgzK1p3Vk1pK1Qxb1dXYjJJYW8KRPHUGj/04TU29CHqXmD9V4kOgQdXRU2s
            GxWXRjjCEPw/nU8K/VzE0/vS5DfCQ/4sYoY31roMyNSkFvFCjgs3Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-30T19:38:34Z"
    mac: ENC[AES256_GCM,data:addlkhc+HFgg33zQp4k9bxZXal8lI0kgnhVVx+8YmUGWCwOkRQgMoIERSXEgnjMQfmybKR9DIpQitLvq6nrS7j0yOFTd3LHcPim9/Dkc2GmKtMv9NpHrmMeK+7XIGbDyA47rck9Rnezkn0YHNWDYY5MTsGmW7XZ51D2510AuXRE=,iv:aMRqyesol9tNK4pNTJ6IKRhzGhgQnb84LQchcvhw8WQ=,tag:U+2VvmYd8zssLidcQgRXlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
