apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:vKnxhRGCPC6hM/aTJNucDMJt5hF6SXXWzWJVRUmKfE99w+xAXjWeug==,iv:L7Qou33i57JrF8j1xDt8NykjYYLiedjyPYXb+LfClSg=,tag:v/FxxEAU25IJ6UrSJf7MXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxj35hpuyzh8zpgsxs3tg40wdm79vttlra35q88sdefdsqh3pgfqfppfjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaekhOTlh1SWtZZk9rN3l0
            VzVjd2pkN3FhVENNRlRRNlA2SWQrTlViSUUwCkJmc1FIZDJ2b2dsN0RoRS8ySjNi
            bWJ0VGNkMFdyWHJNRlROSEJ4aC9NZXcKLS0tIDZDQjVIRWhrVGN5cVVBckRMRUNa
            Slg3VjdQemVTVC9Pbm1HcHNhNEl3bGsKRAWnf/wq2okylKAPDju5CtVjqad0AITm
            kE6XysmyWj0HNoR0T1R5xQVRWBKVLPw9qgOzn4ganhB6BE2lQivaEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-30T19:38:34Z"
    mac: ENC[AES256_GCM,data:Opi+2wnnrhqn7/LMZMn4L9Gts9vbXUzPtUmXBLjls/FISfvc51WwkAL/yJim89LtLvO6A4PUOB8XpRrzm02kMFUaBi6PqC/V8rxj9TKGrrRfNf215CdiMt7Zde6lt6akpUMUeNVGLBIpwD46ThpVZDIvBgeNIYO9/jRsfwJIPOY=,iv:kPZ0tuYR376jkcvEXd/DK0y4WSQe5fxzQz6I+682QNM=,tag:YoWCTsYiAPbFtZVNRlIf7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
