apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:mdzTOfB+7jy1GEN4RGG/qIKXium+JtmcEQ==,iv:XQY4Ox/yk9m5NWesyA4aI/0tDJn8Kgmwu/jvrVWmgPM=,tag:lvKX4x5wWiWAX2Yt2TCkpw==,type:str]
    api-key: ENC[AES256_GCM,data:CEXHewipKFXnYUI4m9zYpQ56qpA+ESmQp+ZGg+XZtfF2BOBgCg==,iv:hic0QN8AQL0w+y8pCNL/hOLIerBWx2PBX2eyP5+9ZUw=,tag:Dvwk7wGl9rLNMEozzKVlBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxj35hpuyzh8zpgsxs3tg40wdm79vttlra35q88sdefdsqh3pgfqfppfjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TWhGc3kyVzlRNy9RbmpD
            am95Z2dDNjNNNHZ0WGZYdDFqYW4zd1NHWW1VCk9HMFFKNjQ5d0ZpQXRPU1ZjUnFi
            djdHLzZ1VldodkpNVW9OSjg0SGhZRmcKLS0tIEdKQnVodThFeUsxbUN3bWFSejRX
            L054VUhnNDBFVUxielE4clpveFpZOW8KjkK+LWbu9CMPoZzWkpVdJEqzvfyjoBg2
            xpy83ZJOUukf0BNKgwagXR+ngseLtM8F8ZnwEQCCSInAf/n/HnMXSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T14:37:50Z"
    mac: ENC[AES256_GCM,data:KJAjSp42oUjbOaNcIjqp5U3p6eoq9AnNsJdYM7Qsy9C7n51o++i6V0Q90nZIEBP1RcL1bFk3KnZwOfYQvuQfCyoUEEJ/NIiEBaIef39Pvyuxsze5ME3HIeFie087ZPelTQXBykvr0SxURTFH+eG0S5UmZAJaBfx4VrBtqa7TPtw=,iv:9UswaNIpx8XaujRowSJtHFHnEyLpOz6wSYcJ5E2VxYo=,tag:ZC6PbYyXP/JRJtVCywF11Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
