apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: networking
type: Opaque
stringData:
    tunnel.json: ENC[AES256_GCM,data:PSA1Z+QXIyVJ0/nBGL+tCB/6LHAXPYE22PV6MKxzsBquA3RVDhOGHts3mE5c70BuswXDnGTvf8WEpvP4KTedzrta1zO91PRYXIg2A72SxTmSClE09BGgx1bL5Gvdp5IhG004k3plyxta2Rl9QBJ+07Y9w3z29Hz6RCnNnYIJ345k8CHUWumJ11TmThlWhPdLeVpH7bIOsrwsTqbmUtJjoLqyxqQ9Y8hYSwStZlsIBDwMedAH6uG7Sw==,iv:hhji9+tylEDDt9/oDVu/M5tm+rqlLw8LWaXsyaLb/6c=,tag:312jprJelVNjlDClPZ0nWA==,type:str]
    #ENC[AES256_GCM,data:Haaya+6zjyO7DNyybJGiyywKUlGIMMChTzLiRqSFUZPTKA==,iv:2VZuAIij9l9WpYKhCcJE9YGvl9gHEhPvir7GpnTc0SY=,tag:wHtEW12SN3lhhtORKUkV9w==,type:comment]
    identity: ENC[AES256_GCM,data:KaDjo/WVRaUGJKN3uTSfHbK9fjFFdBEpF0GSs1sXAmYlHizslZZRngyWP68q3aL/6wSpJ2Dhf3rc/SRB+UNjuiStcFg8mjQYxFyQjwNo,iv:4Sitsm2qxlbDhlapix/XrQcq8BTE5/vk6XLhyHX84Vg=,tag:2dca+oPrO7MklHKQnG2ZWQ==,type:str]
    #ENC[AES256_GCM,data:ytBrAcuRjOf0R15ZgxWb/Hi7FmRgNqYVz19ASsPXHKJ3Ovk/Coj6N+UBBIJTP7Jl8gsLXvpW11y+3+MEk4rQa20nJBlr4fj0p+ji19d2rjLy99jAczIrYJSQbX/dyEoeYivAt8jU,iv:3AYPaECbv1+kw09KDJqBk21k8e2SfmJQIZ+jqj3dmd8=,tag:MEI1FDv8c5CRdctU99iAFQ==,type:comment]
    known_hosts: ENC[AES256_GCM,data:7U0RFGvNFu7PqZdOs4RD3xUSDNldFg1JcXTIRe2sXUfXrIFMkXz0EcLCBaFgxdfs0MJ819LgU+kwgXemTKCC8nF77ypZNzIOlZB+N/r/W6RsRvIeSw==,iv:ncwPa06qhefKjF3MOYyI5v3efr7Jvj0V2ISmBz9vhpA=,tag:dspsDPH1L6oxEtoTrkzKTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxj35hpuyzh8zpgsxs3tg40wdm79vttlra35q88sdefdsqh3pgfqfppfjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbVJSNnBiZStWa1AwRVlx
            UHlnL0VOQWl1eFpLMFg0bm14QUc1ZlZEZ0NrCmo2cmJZNVFWZGZxcG5jM2paNWR0
            aFhqNzNYd0ZKZXg3VDhSWXdweVRDTWcKLS0tIFlmWTZ0eVJRd0dXUUlVaXlIOVow
            OU1tWm1NU1RHRjFYTjhuUExrbkZBQmMKb8nEbNVYPiNZDaOn6alPlEX9T0QSgxEN
            /b2wF/xGoiWzj8ttQ26dqg8wm6VAC3rPv/vZjoiYeOMsxOvc2c/DRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T17:46:06Z"
    mac: ENC[AES256_GCM,data:nzvS1unA6NX5AsgN6h0X/anrfv9nlNqFYtMrhLsgVu305fgcRBKdViRBt/eI5NXvXwB+dBflMd5+GntCQoNd8abzPA+4slm777DkYOlvNlGpzCH/dvfrMXMlEA2l9bzo/cvMDcr7uqW7jvHYgqNSvy2+EEKdiBYmUKTIkH5CUvY=,iv:+pBtqr5NrrDls4YOVwYTrsiyXtxCSmN652mp3jfSjxc=,tag:KOsIqEB6bOfPEEn06ouf6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
