# https://github.com/linuxserver/docker-radarr
# notes on volumes: https://wiki.servarr.com/docker-guide#consistent-and-well-planned-paths
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1h
  values:
    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 4.4.2.6956@sha256:02068de49a62214022efcee0ca8540cff510bb740d7974f81a45758d6cd6043d
    service:
      main:
        ports:
          http:
            port: 7878
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /opt/radarr/config
#        subPath: radarr
      # give access to parent of download folder and tv directory destination
      # https://wiki.servarr.com/docker-guide
#      media:
#        enabled: true
#        existingClaim: media
#        mountPath: /data
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "radarr.${SECRET_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: movie
        hosts:
          - host: &host "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
