apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:djEAWfUppY3aaiDnxH2zFBPqvp0qZ+0ocErPnbA69jQ1voBYpuQ+GYVFCvj4mtaNkvPUFTcm62tgOb5J,iv:i+ASk+H7NB1ACWfRe12o/EAt0Zk94uSbyRhrFdZ5Lms=,tag:hIVnZ6lR4SqwHiX6t93/bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxj35hpuyzh8zpgsxs3tg40wdm79vttlra35q88sdefdsqh3pgfqfppfjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WVpYYXNSMXVwdGhVRnNT
            R0VMSVBheVRWR0ZuVm5FdnNuaUUxZUUyT0RRCnB4L3V2eVNySStRczNWZlRiWUNs
            RTlCYU9ISG10WkFnYUZkdVRVbnlNNHMKLS0tICtLS1BUeFRsamJTMklNMzVCdGh0
            azB5M2VWZE1TNXY5S2wvd25nakFDZFkKE4N5/RzyoXjRjFrch3sOWyDfWN/chrd8
            oUgnjPzttHVZtgvsEkaH+yfluhKjauR412m6CJ24Zewh5r6kKIaukQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T15:40:06Z"
    mac: ENC[AES256_GCM,data:Pao0SWMwAknP0R+p95BmINOtuq31EHtVI+ij/XJkGkcZnlSbQotaanUbFK9HEQ5GvD8hCIFkzABsN8ok+QjHbHs6c1YY4/xiKcdEj799qgjDoOixciiG5mtr/qj3FsOvriXV1C8dhiOUr958dzx/HSDisE9FxQa1Wdnt0I7YWd0=,iv:AUKxERAcVFPjOMb0437VGbfUr505sNZYLXz13gbvYog=,tag:XFghkSAyW6hkS68fXP10bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
