apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:HPqFj16iM4Vt+tngc4QHS4IFqfPsVpqZVNNObnmpS6fqg0GLRHSQGHeCOEfuYx8E5/GTCSgm0QzeIOWL,iv:KRdh+QfAT4jRcnyPDWd7+ygCKK01r7RwSW8th88PLrs=,tag:NBLZUpvBjCSjUnboT8Z6TQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxj35hpuyzh8zpgsxs3tg40wdm79vttlra35q88sdefdsqh3pgfqfppfjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZjNjSkNQQ3pGWlFmak1Y
            SzJPVVIyOGxqeGFET2loMURxZW9BOS9waUhnCjcyWHpkVFM4MW5NVkhMZ05nRXFF
            K01sNjlLYS9TVjNiSVNrVGNzOExOVkEKLS0tIDVCNHVXMzN0aFR1azVGb3dCckEv
            WnJiZFlmdjR5UGRvUlUyTzBLVHVYSzQKbnhXQWqeKJDnX94yHkaR9dBORdiY9c+i
            4tzbI2FzXAJj4vV16U9LiciMJcRBpeYZrPG683kZuSNJHIeUjWdZgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-30T19:38:35Z"
    mac: ENC[AES256_GCM,data:4r4yen8kMUg66XxHI06ouwH5ub6+jWwOG+mE/wez4OES2hU7IT76Yr4Tp0SsYlg7vf5cu0zs4zyh8uOCyC3wv/VDnxWpKOy6tpp+xoIIP4CL3NJu2n09idrt5zoU1sNbhzwxPu7BSYkK2WrUVEg04178J5x0e5yd0Y2g9OtYQIQ=,iv:UEzhFEXFuMA3RMqF9BdymPdzcuUN+nkSDyx2s8S7JZc=,tag:zn72HtJN6R1ei70u6QuIzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
