---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: "192.168.4.200"
  METALLB_LB_RANGE: "192.168.4.70-192.168.4.80"
  METALLB_K8S_GATEWAY_ADDR: "192.168.4.70"
  METALLB_INGRESS_ADDR: "192.168.4.80"
