apiVersion: v1
metadata:
    name: cloudflared-credentials
    namespace: networking
    annotations:
        reloader.stakater.com/match: "true"
kind: Secret
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:5+NT1m5TJ4qUUJrAk8itLFAtqHHinwBOZQnpNsaxMmeZ2/7Sg+ZkNyDDSDFo9z45yGjNt8dF0OxMCmwpA8lj8vOWQ/IG+RVnddk9I2agtFDoBo3E/KjdhsWmSn2VvwZ2FGnS5wO1rmDgG2X+/yKnuh975JsvBQbulE2TnJCD+XB4K8zoLEaKLb684BqCeMxXZw3fvS1UD257+dKJa2O0Fj0=,iv:xk01F2p7xdf+NIpl6nb89wTbZwhLaryIJQbHqT8QgH8=,tag:dtebx9tk4EOLT49ma7SE1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxj35hpuyzh8zpgsxs3tg40wdm79vttlra35q88sdefdsqh3pgfqfppfjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb2VsS3N1M2RINE0wQjlw
            UFoybzhuQ011dVNBZGZWME5MNnNqdUlvam5RCkVxd1o2OVdZZHl2OFN3VGxLWG9M
            TUlmbGwxbjBBZXYvT3pWMGlpS3BTSncKLS0tIHNmaC9DTE5uZk9tQ1RuT2tuYUpW
            MW94RlJmdFp5SXhyYjhlVEdoUllGNkEKYD8nWFJCASl2zijRrfOu3KHLuzKzVKMv
            Qcdt0j7DmDj5FiAw14XrOP2oAlmnLbK8kIVQsGdoTEY1PixhVDxnOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T16:06:37Z"
    mac: ENC[AES256_GCM,data:e8cwUBKdG0oVAuqjbFWWJMNrkKU9uV04kYJ/YE9MyhLU5e4t9OC3kZBf78Jayh+nLx8hwSzUUxSAcerCJ8byb1vcrrCXTXEo3PiT8WOKCvSeNluMqkt8jkFY/9xQzeBszsTc0zp+wOOKPkyGPZd5dPfruoBMxrDIEnHGZQ2hdbQ=,iv:u7JsoTRnonxiWbpeQvNZ3CoF84mNTEjut3KzDkRcK/Q=,tag:GsV2O2HDhPkvzsNhA/Ze2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
