# yamllint disable
apiVersion: v1
metadata:
    name: cloudflared-credentials
    namespace: networking
    annotations:
        reloader.stakater.com/match: "true"
kind: Secret
type: Opaque
stringData:
    credentials.json:
        - ENC[AES256_GCM,data:Izj6MWmY8rXeXP+JDrk7gQGTEIclhrES1mqAR7bfCTQNlEPiVXy5U+Kmqfrcz7CoOGlrKdfvwEXGpgyevFZMhpv5OOyFfVq0nA8m4Ymzb63GX0J1ukFObpC3mnUT0tSOquatwINMrUUgGqbdXWp/9AlDyWi/QyYD5pp795/NoGfoqARLldPC+ZmiBYHxh6bvyePYYImJFTV+26ZGaaq3u1debA==,iv:nRL/gjnRy6DX6IuIVhMJksCtH8YoEUxL1VXCLrytuLE=,tag:HfCdX/a5jw//o9bCF4bsjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxj35hpuyzh8zpgsxs3tg40wdm79vttlra35q88sdefdsqh3pgfqfppfjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb2VsS3N1M2RINE0wQjlw
            UFoybzhuQ011dVNBZGZWME5MNnNqdUlvam5RCkVxd1o2OVdZZHl2OFN3VGxLWG9M
            TUlmbGwxbjBBZXYvT3pWMGlpS3BTSncKLS0tIHNmaC9DTE5uZk9tQ1RuT2tuYUpW
            MW94RlJmdFp5SXhyYjhlVEdoUllGNkEKYD8nWFJCASl2zijRrfOu3KHLuzKzVKMv
            Qcdt0j7DmDj5FiAw14XrOP2oAlmnLbK8kIVQsGdoTEY1PixhVDxnOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T16:24:39Z"
    mac: ENC[AES256_GCM,data:QUTz+ENcphOoq+UKXsq807pdR9y9YjwexgnRE3nY6TuQGfSO2qKRWXhNP/k4SFdRehHq+GIa+0H3uIFVVL2+A+e8BVfk/YJKkyHQvrsoW5/JDX3VNvdud/M9lzhF7+J2fwQsuPitzPtB1vW5kMmcvFuaojDhAW/XFevRZ1l4cnU=,iv:0bIc3RegpbcCSCx2rpHqCk6XjBA6P27zBm8Yz7c8N/Y=,tag:Iz/8wq5nmR/N6LDEVTOICg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
